export const FETCH_ACTIVESTUDENT_REQUEST = "FETCH_ACTIVESTUDENT_REQUEST"
export const FETCH_ACTIVESTUDENT_SUCESS = "FETCH_ACTIVESTUDENT_SUCESS"
export const FETCH_ACTIVESTUDENT_FAILURE = "FETCH_ACTIVESTUDENT_FAILURE"